services:
  postgres:
    image: postgres:14.0
    container_name: postgres-container
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      MAX_RELATIONAL_DEPTH: ${MAX_RELATIONAL_DEPTH}
    ports:
      - '5433:5432'
    command:
      - postgres
      - -c
      - ssl=off
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:6
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  app:
    container_name: app-container
    image: directus/directus:11.5.1
    command:
      [
        '/bin/sh',
        '-c',
        ': && node /directus/cli.js bootstrap && npx directus schema apply --yes snapshots/app.yml && node /directus/cli.js start',
      ]
    ports:
      - '8055:8055'
    volumes:
      - ./extensions:/directus/extensions
      - ./snapshots:/directus/snapshots
      - ./migrations:/directus/migrations
      - ./uploads:/directus/uploads
    depends_on:
      postgres:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file: ./.env
    environment:
      DB_CLIENT: 'pg'
      DB_HOST: 'postgres'
      DB_PORT: '5432'

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_DATABASE: ${DATABASE_NAME}
      DB_USER: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      MIGRATIONS_PATH: './migrations/'
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: ${CLIENT_SRC}
      EXTENSIONS_AUTO_RELOAD: true

      CACHE_ENABLED: "true"
      CACHE_TTL: "7 days"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      PUBLIC_URL: "http://localhost:8055"
volumes:
  postgres_data:
  redis_data:
